### ISSUE TITLE
IE Launcher without "-extoff" flag

### ISSUE THREAD

**Issue by Artiga** [karma-runner/karma-ie-launcher#27]
Hi, this is not really an coding issue (sorry if here is not the right place to post that), but I wanna know if there's a way to launch IE without the "-extoff" flag.

I already did that changing the original launcher code, but If possible I prefer a manner where I dont have to modify third party code. Maybe using preprocessors but I dont know how ...

Someone could help me with that?

Thx

**Comment by NateEag** [comment]
This is a major issue for me at $DAYJOB.

Our Windows desktops are locked down tightly, and IE will not start if `-extoff` is passed, so that users can't work around the controls IT has added to IE.

Thus, we cannot use the stock karma IE launcher.

I've currently just manually fixed this in index.js.

It would be great to see this fixed.

**Comment by NateEag** [comment]
Awesome. Thanks!
