### ISSUE TITLE
IE 11 Disconnected (1 times), because no message in 10000 ms.

### ISSUE THREAD

**Issue by davidreher** [karma-runner/karma-ie-launcher#45]
Hey there,

got a weird error, since 2016/06/17: When running my scripts headless with jenkins, my tests are failing with the above error message.

```
[15:10:03] Starting 'test'...
ts-loader: Using typescript@1.8.10 and e:\ci\aol\jenkins_home\jobs\si.aol.adj - Integration\workspace\tsconfig.json
[32m20 06 2016 15:10:51.675:INFO [karma]: [39mKarma v0.13.22 server started at http://localhost:9876/
[32m20 06 2016 15:10:51.691:INFO [launcher]: [39mStarting browser IE
[32m20 06 2016 15:10:55.845:INFO [IE 11.0.0 (Windows 7 0.0.0)]: [39mConnected on socket /#rD65BSHrksOcu95yAAAA with id 77585709
[33m20 06 2016 15:11:05.867:WARN [IE 11.0.0 (Windows 7 0.0.0)]: [39mDisconnected (1 times), because no message in 10000 ms.

[15:11:06] 'test' errored after 1.03 min
```

I don't get any other output nor any other errors. When running the script interactively on the exact same server works. Any ideas?

**Comment by davidreher** [comment]
Hm, was a proxy issue in my setup.

**Comment by ashes999** [comment]
I experienced a similar case. In my case, the issue was IE11: when the browser launched, it popped up a modal asking if it should use the default settings or not. That prevented Karma from proceeding.

I couldn't easily tell, because this was on a build node, and nobody ever remotes in (or uses IE) on that node. I remoted in and ran karma manually, and immediately saw the problem.

I fixed it by launching IE by hand and selecting a setting; subsequent builds ran and passed.
